### PR TITLE
feat: Implement propagated arguments.

### PR DESCRIPTION
**Pull request by DanCardin**
Also significantly refactors the native parser backend internals to ease the implementation of the feature.

### CODE REVIEW

**Comment by DanCardin** [comment]
@pawamoy An early attempt at a solution for [this](https://github.com/DanCardin/cappa/discussions/162). e.g. `Arg.propagate=True`. I have yet to deal with help generation, docs, or other fallout, but it's largely passing the existing set of tests.

I decided `global` a-la-clap would be a bad name because it's a python keyword, and because it's not really global (even in clap), it's propagated downward from the point of registration. Although i'm not married to the name, if you have a better suggestion. Off the top of my head, I could imagine `inherit`.

It also has (imo logical) lower precedence and doesn't physically conflict with an identically named arg defined in a more specific subcommand. Idk what exactly would be the usecase for this, but it seemed preferable to being too restrictive and would have been more challenging to implement probably.

lmk what you think, and if it solves your issue.

**Comment by pawamoy** [comment]
Thanks for the mention @DanCardin, let me try this branch.

**Comment by pawamoy** [comment]
Thanks again for the amazing work you put in Cappa @DanCardin. Here's my initial feedback:

1. The help message of subcommands does not show the propagated options. Note that I'm declaring each option in its own class, then inheriting from these classes in command classes. Something like:
  
  ```python
  
  @dataclass(kw_only=True)
  class LogLevelPathOptions:
      """Log level and path options."""
  
      log_level: An[
          Literal["TRACE", "DEBUG", "INFO", "SUCCESS", "WARNING", "ERROR", "CRITICAL"],
          cappa.Arg(short="-L", long=True, parse=str.upper, group=_GROUP_GLOBAL, propagate=True),
          Doc("Log level to use when logging messages."),
      ] = "INFO"
  
      log_path: An[
          str | None,
          cappa.Arg(short="-P", long=True, group=_GROUP_GLOBAL, propagate=True),
          Doc("Write log messages to this file path. (Default: stderr)"),
      ] = None
  
  
  @cappa.command()
  @dataclass(kw_only=True)
  class CommandMain(BaseCommand, LogLevelPathOptions):
      ...
  ```

2. The parser still seems to propagate them, because passing such an option to a subcommand doesn't make it fail.
3. However, the big issue to me here is that we go from explicitness (each command properly declares all its options statically) to implicitness/magic (subcommands have more options than they show). This implicitness does not play well with type-checkers: they are now warning me that, for example, such and such command class doesn't have a `self.conf_path` attribute.
4. Worse, these class *indeed* do not have these attributes! It makes sense since they're only declared on the main command. But as I shown in another discussion, I'm actually using these global options within subcommands' `__call__` methods. Now that these options aren't there anymore, am I supposed to use dependencies somehow?

I note however that my previous setup didn't work either: while all commands have each global option, they only receive the argument passed from the CLI when it's passed at the right position:

```console
# Command "add repo" receives the conf path.
% pypi-insiders repos add -c path/to/conf.toml
path/to/conf.toml

# But here it doesn't and uses the default!
% pypi-insiders repos add -c path/to/conf.toml
/home/pawamoy/.config/pypi-insiders/repos.json
```

**Comment by pawamoy** [comment]
Amusingly, `propagate` sounds like it would do exactly this: propagate values to subcommands, even if passed to upper commands :smile:

**Comment by pawamoy** [comment]
I realize I'm not always easy to follow ('cause I don't know what I'm doing most of the time haha), so please don't hesitate to ask for more details or for actual, working pieces of code :slightly_smiling_face:

**Comment by DanCardin** [comment]
Maybe i'm not understanding what your example code is doing, but it feels like there's an expectation mismatch based on your point 3/4.

The premise of this feature would be that you declare an option (with propagate) at the highest level that you want it available (e.g. `CommandMain` for you) and no where else. Then your individual subcommands (or a global dep) can simply depend on `CommandMain` like
```python
def logging(command: CommandMain):
    configure_logging(command.log_level)

invoke(CommandMain, deps=[logging])
```
And regardless of where the user supplied the argument value, the value would be routed into the `CommandMain` instance, so there's a single object point from which to reference the argument for configuration.

So while your CLI shape will allow for `--log-level` at any subcommand level, none of the other command objects at the python type system level would have a `log_level` attribute. So that's why i'm not sure I understand your points 3/4.

If this all sounds right and i'm just missing something fundamental, lmk!

**Comment by pawamoy** [comment]
OK thanks for your answer! It's starting to register. I believe I can add dependencies to my `__call__` methods, like `def __call__(self, main: CommandMain):` and then use this `main` instance to pick up the values I want. However it ties the `__call__` method to Cappa's invocation logic, which kinda prevents me from using the command dataclasses directly (or at least easily).

**Comment by pawamoy** [comment]
Right, I'm getting somewhere:

```python
@cappa.command(
    name="add",
    help="Add insiders repositories.",
    description="Add a repository to the watched repositories.",
)
@dataclass(kw_only=True)
class CommandReposAdd(BaseCommand, RepositoriesPackagesOption):
    """Command to add a repository to the watched repositories."""

    def run(self) -> int:  # noqa: D102
        print(self.conf_path)
        return 0
        repos = RepositoryConfig(self.conf_path)
        repos.add_repositories(dict(self.repositories))
        return 0

    def __call__(self, repos: CommandRepos, main: CommandMain) -> int:  # noqa: D102
        if self.conf_path == DEFAULT_CONF_PATH:
            if repos.conf_path != DEFAULT_CONF_PATH:
                self.conf_path = repos.conf_path
            elif main.conf_path != DEFAULT_CONF_PATH:
                self.conf_path = main.conf_path
        return super().__call__()
```

This is now doing what I want. And I can still easily call `CommandReposAdd` directly, because its `run` method is "standalone". If you prefer, `__call__` is interfacing with Cappa, while `run` is the regular programmatic-use method.

Now, if Cappa was able to do that automatically, that would be fantastic, but it might not be easy to do, or maybe it's just too specific to my use-case.

**Comment by pawamoy** [comment]
Maybe there are easier things to do like supporting a "parent commands" dependency?

```python
def __call__(self, commands: cappa.ParentCommands):  # or list[cappa.Command]?
    ...
```

**Comment by DanCardin** [comment]
So I did have a bug in the original impl (pushed update) which didn't properly propagate it down past 1 level of subcommand. hope that didn't contribute too much to confusion of the feature!

The fact that your example code is still referencing `log_conf` relative to different python object levels makes me still feel like there's an impedance mismatch here.

This is what I imagine your command definition/usage of the feature would look like
```python
from __future__ import annotations
from typing import Annotated, Literal
from dataclasses import dataclass
import cappa

@dataclass
class Main:
    log_level: Annotated[Literal['debug', 'info'], cappa.Arg(short=True, propagate=True)] = 'debug'
    sub: cappa.Subcommands[Repo | None] = None

    def __call__(self, output: cappa.Output):
        output.output('main')

@dataclass
class Repo:
    sub: cappa.Subcommands[Add | Remove | None] = None

    def __call__(self, output: cappa.Output):
        output.output('repo')

@dataclass
class Add:
    name: str

    def __call__(self, main: Main, output: cappa.Output):
        if main.log_level == 'info':
            output.output('maybe i want to use this in a command still')
        output.output(f'add {self.name}')

@dataclass
class Remove:
    name: str

    def __call__(self, output: cappa.Output):
        output.output(f'remove {self.name}')

def configure_logging(command: Main, output: cappa.Output):
    output.output(f"Log level: {command.log_level}")

cappa.invoke(Main, deps=[configure_logging])
```

```bash
❯ python test.py
Log level: debug
main

❯ python test.py -l info
Log level: info
main

❯ python test.py repo -l info
Log level: info
repo

❯ python test.py repo remove foo -l info
Log level: info
remove foo

❯ python test.py repo add foo -l info
Log level: info
maybe i want to use this in a command still
add foo
```

---

What it seems like you're after is explicitly (though inheritance) ending up with identical Args at different levels of subcommand, but where the value is written simultaneously to every class in the tree because they're the "same" argument.

With the goal being to be able to arrive at the `log_level` value in the context of a single subcommand's instance without needing your parent command's instances available at call time.

I dont know how strong that need is, because i dont know the alternative non-cappa context in which you'd be calling to the instance, but it **feels** more composable and consistent to me to do it the way i wrote above, even if it requires instantiating the parent command object (because that's what's going on when you use it inside cappa.

With that said, I could imagine the current impl to be the precursor to a more general argument "identity" feature. Off the top of my head:

```python
class Main:
    foo: An[..., Arg(identity='foo')]

class Elsewhere:
   bar: An[..., Arg(identity='foo')]
```

where two args with identical identities would write the given value every destination of the same identity. At least that's what it sounds like you're asking for (if the above example wasn't enough)

Although, i think ideally you'd be satisfied with the example above, because i'm not sure whether i think this is a good idea or not :P

**Comment by pawamoy** [comment]
Wow, thanks.

So, the logging example is not good, because I don't actually use the `log_level` or `log_path` values in subcommands, so it works well as a global dependency.

But the `conf_path` value is used in subcommands, like:

```python
class CommandReposList(BaseCommand):
    """Command to list the watched repositories."""

    def __call__(self) -> int:  # noqa: D102
        repos = RepositoryConfig(self.conf_path)
        ...
```

With propagation, I don't have `conf_path` on `CommandReposList`, so I have to pick it up from `CommandMain`. To do this I inject the main command instance in the `__call__` method:

```python
class CommandReposList(BaseCommand):
    """Command to list the watched repositories."""

    def __call__(self, main: CommandMain) -> int:  # noqa: D102
        repos = RepositoryConfig(main.conf_path)
        ...
```

That works well, but makes it a bit harder to use elsewhere. For example:

```python
from pypi_insiders.cli import CommandMain, CommandReposList

main_cmd = CommandMain(conf_path="some/path.toml")
repo_list_cmd = CommandReposList()
repo_list_cmd(main_cmd)
```

...instead of just:

```python
from pypi_insiders.cli import CommandReposList

repo_list_cmd = CommandReposList(conf_path="some/path.toml")
repo_list_cmd()
```

---

This is really just an ergonomics nitpick! The propagation feature and the example above look really good to be honest, and I would expect most users to go with it.

> I dont know how strong that need is

Yep, me neither, I'm just experimenting and trying to achieve subjective perfection with Cappa :slightly_smiling_face: In other projects I'm calling third-party CLIs programmatically, and some of them make it extremely painful, so I'm trying to do better.

---

I have experimented a bit more on my side, and ended up with this:

```python
@dataclass(kw_only=True)
class BaseCommand(CommonOptions):
    """Base command class."""

    def run(self) -> int:
        """Run the command."""
        raise NotImplementedError

    def _propagate_options(self, *parents: BaseCommand) -> None:
        # Propagate options from parent commands to the current one.
        for option in asdict(self):
            self_value = getattr(self, option, _UNSET)
            class_value = getattr(type(self), option, _UNSET)
            if self_value is class_value:
                for parent in parents:
                    parent_value = getattr(parent, option, _UNSET)
                    if parent_value is not _UNSET and self_value != parent_value:
                        setattr(self, option, parent_value)
                        break


    def __call__(self) -> int:  # noqa: D102
        configure_logging(self.log_level, self.log_path, allow="pypiserver")
        return self.run()


@cappa.command(
    name="add",
    help="Add insiders repositories.",
    description="Add a repository to the watched repositories.",
)
@dataclass(kw_only=True)
class CommandReposAdd(BaseCommand, RepositoriesPackagesOption):
    """Command to add a repository to the watched repositories."""

    def run(self) -> int:  # noqa: D102
        repos = RepositoryConfig(self.conf_path)
        repos.add_repositories(dict(self.repositories))
        return 0

    def __call__(self, repos: CommandRepos, main: CommandMain) -> int:  # type: ignore[override]  # noqa: D102
        self._propagate_options(repos, main)
        return super().__call__()
```

With this I can use `CommandReposAdd` directly without having to also instantiate `CommandRepos` or `CommandReposMain`. The last tiny pain point is that I have to manually declare the parent commands as dependencies in the `__call__` methods, where relevant.

**Comment by pawamoy** [comment]
I thought more about it, and I'm definitely optimizing too much for reusability. I don't think I'll be myself reusing these dataclasses like I describe. It's like trying to factorize everything in dozens of little functions: doesn't make the code more readable or maintainable. Argument propagation + dependencies make things more elegant. And my way of declaring each option in its own class doesn't make sense either, as options are often used in conjunction with other options. So, I'll tame the consistency demon in me, and opt for practicality. Thanks for bearing with me!

**Comment by pawamoy** [comment]
By the way I prefer `propagate` to `inherit`, because `inherit` would reinforce the (wrong) idea that a subcommand is some kind of a subclass of a command, which they're not. My 2 cents :smile:

**Comment by DanCardin** [comment]
> By the way I prefer propagate to inherit, because inherit would reinforce the (wrong) idea that a subcommand is some kind of a subclass of a command, which they're not. My 2 cents 😄

Fwiw, you'd be annotating an argument. so in my mind, it's saying "this argment will be inherited", but that's a fair concern, it's certainly already a used term in classes (which i initially thought was a boon) which might be open to confusion.

I dont have any other ideas though, so maybe propagate is fine.

**Pull request merged**
